# Generated by Django 5.0.6 on 2024-06-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project_Rezome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('sit_type', models.CharField(choices=[('O', 'Online Learning'), ('E', 'E-Commerce')], max_length=1)),
                ('site_cover', models.ImageField(upload_to='covers/')),
                ('site_linke', models.CharField(max_length=250)),
            ],
        ),
    ]
