# Generated by Django 5.0.6 on 2024-06-21 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_rezome',
            name='sit_type',
            field=models.CharField(choices=[('Online Learning', 'Online Learning'), ('E-Commerce', 'E-Commerce')], max_length=50),
        ),
    ]
