# Generated by Django 5.0.6 on 2024-06-21 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_project_rezome_sit_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_rezome',
            name='site_cover',
            field=models.ImageField(blank=True, upload_to='covers/'),
        ),
    ]
