# Generated by Django 5.0.6 on 2024-06-24 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_project_rezome_site_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_rezome',
            name='site_cover',
            field=models.ImageField(blank=True, upload_to='covers/'),
        ),
    ]
